WIP on create vcard
MigaduMail/naiveical pull request #1
Opened 2023-03-23 09:03 UTC by DimitrijeDimitrijevic

2023-03-23 09:19 UTC, swerter requested changes

2023-03-23 09:19 UTC, swerter commented on lib/vcard/creator.ex
> +
please could you add a full vcard example here for reference?

2023-03-23 09:19 UTC, swerter commented on lib/vcard/creator.ex
> +    emails = extract_additional_properties(opts, :email)
not sure if you really need a specific function just to extract a key with Keyword.has_key?

2023-03-23 09:19 UTC, swerter commented on lib/vcard/creator.ex
> +  def extract_additional_properties(opts, :email, additional_properties) do
If you like this functions, maybe rename it to get_properties instead of extract_...

2023-03-23 09:19 UTC, swerter commented on lib/vcard/creator.ex
> +    comp = if is_nil(c.street), do: ";", else:
are you sure the else: clause is correct like this?

2023-03-31 09:00 UTC, DimitrijeDimitrijevic commented on lib/vcard/creator.ex
> +
I have added one which I use as reference for creating vcard, its from thunderbird client.

2023-03-31 09:01 UTC, DimitrijeDimitrijevic commented on lib/vcard/creator.ex
> +    emails = extract_additional_properties(opts, :email)
It can be done with opts[:key], but it can explode if not key exists in list, in my opinion this is safer way.

2023-03-31 09:01 UTC, DimitrijeDimitrijevic commented on lib/vcard/creator.ex
> +  def extract_additional_properties(opts, :email, additional_properties) do
Done, thanks :)

2023-03-31 09:08 UTC, merged